# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\get_token.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseGetToken(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"platform": ["android", "ios"]}))
    def test_start(self, param):
        super().test_start(param)

    config = Config("获取Token").export(*["token"])

    teststeps = [
        Step(
            RunRequest("用户登录")
            .post("${ENV(base_url)}/auth/login")
            .with_headers(**{"version": "${ENV(version)}", "platform": "$platform"})
            .with_json(
                {
                    "email": "${ENV(email)}",
                    "password": "${ENV(password)}",
                    "loginType": 1,
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.data.email", "zelun.su@amperetime.com")
            .assert_contains("body.data", "token")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetToken().test_start()
