# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\get_version.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from testcases.get_token_test import TestCaseGetToken as GetToken


class TestCaseGetVersion(HttpRunner):

    config = Config("获取版本信息")

    teststeps = [
        Step(RunTestCase("获取token").call(GetToken).export(*["token"])),
        Step(
            RunRequest("获取版本信息")
            .get("${ENV(base_url)}/version/last")
            .with_headers(
                **{
                    "Authorization": "Bearer $token",
                    "platform": "${ENV(platform)}",
                    "version": "${ENV(version)}",
                }
            )
            .validate()
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
            .assert_contains("body.data", "versionNum")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetVersion().test_start()
