# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\get_version.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseGetVersion(HttpRunner):

    config = Config("获取版本信息").export(*["version"])

    teststeps = [
        Step(
            RunRequest("获取版本信息")
            .get("${ENV(base_url)}/version")
            .extract()
            .with_jmespath("body.data.version_num", "version")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
            .assert_contains("body.data", "version_num")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetVersion().test_start()
