# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\get_token.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from testcases.get_version_test import TestCaseGetVersion as GetVersion


class TestCaseGetToken(HttpRunner):

    config = Config("获取Token").export(*["token", "version"])

    teststeps = [
        Step(RunTestCase("获取版本信息").call(GetVersion).export(*["version"])),
        Step(
            RunRequest("登录")
            .post("${ENV(base_url)}/auth/login")
            .with_headers(**{"version": "$version"})
            .with_json(
                {
                    "email": "${ENV(email)}",
                    "password": "${ENV(password)}",
                    "login_type": 1,
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetToken().test_start()
