# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\login.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLogin(HttpRunner):

    config = Config("用户登录").export(*["token"])

    teststeps = [
        Step(
            RunRequest("用户登录")
            .post("${ENV(base_url)}/auth/login")
            .with_headers(
                **{"version": "${ENV(version)}", "platform": "${ENV(platform)}"}
            )
            .with_json(
                {
                    "email": "${ENV(email)}",
                    "password": "${ENV(password)}",
                    "loginType": 1,
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.data.email", "zelun.su@amperetime.com")
            .assert_contains("body.data", "token")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
