# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases\send_verification_code.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from testcases.get_token_test import TestCaseGetToken as GetToken


class TestCaseSendVerificationCode(HttpRunner):

    config = Config("发送验证码校验")

    teststeps = [
        Step(RunTestCase("获取版本信息/Token").call(GetToken).export(*["version", "token"])),
        Step(
            RunRequest("邮箱已注册的情况下，发送注册验证码")
            .post("${ENV(base_url)}/auth/send_verification_code")
            .with_headers(**{"version": "$version"})
            .with_json({"email": "zelun.su@amperetime.com", "type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 10051404)
            .assert_equal("body.message", "The email is repeated")
        ),
        Step(
            RunRequest("邮箱已注册的情况下，发送找回密码验证码")
            .post("${ENV(base_url)}/auth/send_verification_code")
            .with_headers(**{"version": "$version"})
            .with_json({"email": "zelun.su@amperetime.com", "type": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseSendVerificationCode().test_start()
