# NOTE: Generated By HttpRunner v4.3.5
# FROM: api\feedback.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from comm.get_token_test import TestCaseGetToken as GetToken


class TestCaseFeedback(HttpRunner):

    config = Config("用户反馈接口校验")

    teststeps = [
        Step(RunTestCase("获取token").call(GetToken).export(*["token"])),
        Step(
            RunRequest("新增用户反馈")
            .post("${ENV(base_url)}/feedback/save")
            .with_headers(
                **{
                    "Authorization": "Bearer $token",
                    "platform": "${ENV(platform)}",
                    "version": "${ENV(version)}",
                }
            )
            .with_json(
                {
                    "sn": 123456789123456789,
                    "info": "${generate_random_string(300)}",
                    "contactInformation": "联系方式",
                }
            )
            .validate()
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseFeedback().test_start()
