# NOTE: Generated By HttpRunner v4.3.5
# FROM: api\get_version.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from comm.get_token_test import TestCaseGetToken as GetToken


class TestCaseGetVersion(HttpRunner):

    config = Config("获取版本信息接口校验")

    teststeps = [
        Step(RunTestCase("获取token").call(GetToken).export(*["token"])),
        Step(
            RunRequest("获取版本信息")
            .get("${ENV(base_url)}/version/last")
            .with_headers(
                **{
                    "Authorization": "Bearer $token",
                    "platform": "${ENV(platform)}",
                    "version": "${ENV(version)}",
                }
            )
            .extract()
            .with_jmespath("body.data.versionNum", "nowVersion")
            .validate()
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
            .assert_contains("body.data", "versionNum")
        ),
        Step(
            RunRequest("版本对比-存在新版本")
            .get("${ENV(base_url)}/version/last")
            .with_params(**{"version": "0.0.1"})
            .with_headers(
                **{
                    "Authorization": "Bearer $token",
                    "platform": "${ENV(platform)}",
                    "version": "${ENV(version)}",
                }
            )
            .validate()
            .assert_equal("body.code", 10051412)
            .assert_equal("body.message", "The app version not is the latest version")
        ),
        Step(
            RunRequest("版本对比-相同版本")
            .get("${ENV(base_url)}/version/last")
            .with_params(**{"version": "$nowVersion"})
            .with_headers(
                **{
                    "Authorization": "Bearer $token",
                    "platform": "${ENV(platform)}",
                    "version": "${ENV(version)}",
                }
            )
            .validate()
            .assert_equal("body.code", 10051411)
            .assert_equal("body.message", "The app version is the latest version")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetVersion().test_start()
